language: android
android:
  components:
    - platform-tools
    - tools
    - android-25
    - build-tools-25.0.2

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
