language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - android-25
    - build-tools-25.0.2

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - chmod +x ./gradlew 
  "./gradlew build"
